spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/shyamradhekumartech/moneybank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "6963FB8797B97EAC6B5B37A8D79C2"

server:
  port: 8071