spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config"
          search-locations: "file:///Users//java//Desktop//microservices//section6//config"

server:
  port: 8071